name: firebase-ci-cd

on: 
  push:
    branches: ['master']
  workflow_dispatch:

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      # プロジェクトルートの依存関係をインストール
      - name: Install Dependencies
        run: npm ci

      # プロジェクトのビルド
      - name: Build
        run: npm run build

      # テストの実行
      - name: Run Tests
        run: npm run test

      # Functions用の依存関係をインストール
      - name: Install Functions Dependencies
        run: cd functions && npm ci

      # Firebase CLIのインストール
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # サービスアカウントの認証情報をファイルに書き出し
      - name: Create Service Account Key File
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CELEBRATION_PLANNER }}' > ${{ github.workspace }}/service-account.json

      # 環境変数の設定とFunctions/Hostingのデプロイ
      - name: Deploy to Firebase
        run: |
          # 環境変数の設定
          export GOOGLE_APPLICATION_CREDENTIALS="${{ github.workspace }}/service-account.json"
          
          # Functionsの環境変数を設定
          firebase functions:config:set \
            gemini.api_key="${{ secrets.GEMINI_API_KEY }}" \
            domain.allow="${{ secrets.ALLOW_DOMAIN }}" \
            openweather.api_key="${{ secrets.OPENWEATHER_API_KEY }}" \
            rakuten.app_id="${{ secrets.RAKUTEN_APP_ID }}" \
            google.places_api_key="${{ secrets.GOOGLE_PLACES_API_KEY }}"
          
          # FunctionsとHostingをデプロイ
          firebase deploy --only functions,hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/service-account.json

      # サービスアカウントキーファイルの削除
      - name: Cleanup Service Account Key File
        if: always()
        run: rm -f ${{ github.workspace }}/service-account.json
