name: firebase-ci-cd

on: 
  push:
    branches: ['master']
  workflow_dispatch:

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      # フロントエンドのビルド
      - name: Build Frontend
        run: npm ci && npm run build
      - name: Test Frontend
        run: npm run test
      # Functionsのビルド
      - name: Build Functions
        run: cd functions && npm install && npm run build
      # Firebase CLIのインストール
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      # デプロイ
      - name: Deploy to Firebase
        run: firebase deploy --only hosting,functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          ALLOW_DOMAIN: ${{ secrets.ALLOW_DOMAIN }}
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          RAKUTEN_APP_ID: ${{ secrets.RAKUTEN_APP_ID }}
          GOOGLE_PLACES_API_KEY: ${{ secrets.GOOGLE_PLACES_API_KEY }}
